start_date: 2022-11-01
end_date: 2025-03-17
model_name: cwchang/llama-3-taiwan-8b-instruct
companys:
  # - 廣達
  # - 緯創
  - 台積電
  # - 創意
  # - 世芯
  # - 智原
  # - 智邦
  # - 日月光
  # - 台達電
  # - 光寶科
  # - 群光
  # - 奇鋐
  # - 金像電
  # - 嘉澤
  # - 技嘉
  # - 緯穎
  # - 英業達
  # - 鴻海
  # - 聯發科
  # - 聯茂
