version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    ports:
      - "11434:11434"
    volumes:
      - ~\Documents\ollama-data:/root/.ollama
    restart: always